# BarrelAttack

COMMENT_PRESS_BUTTON=Press Any Button
COMMENT_HAKUSHUDE=Clap to Launch!
COMMENT_PLAYER1_READY=Player 1 Ready?
COMMENT_PLAYER2_READY=Player 2 Ready?
COMMENT_PLAYER3_READY=Player 3 Ready?
COMMENT_PLAYER4_READY=Player 4 Ready?
COMMENT_EMPOWER=Drumroll to Power Up!
COMMENT_DO_ADJUST=Adjust your aim by Tapping L or R!
COMMENT_ORDER_CHANGED=Try scoring from lowest to highest!
COMMENT_BADGE=L or R to Select　START/PAUSE to Confirm.

EXPLAIN_1_CAP=How to play Banana Attack
EXPLAIN_1_CON1=・Drumroll to power up.
EXPLAIN_1_CON2=・Clap when the power's up.
EXPLAIN_1_CON3=・Aim by tapping L or R.
EXPLAIN_2_CAP=Multiplayer Rules
EXPLAIN_2_CON1=・The player who isn't launched
EXPLAIN_2_CON2=can shake the tree.
EXPLAIN_2_CON3=Hit L or R to shake it!
EXPLAIN_3_CAP=Single Player Rules
EXPLAIN_3_CON1=・Launch 3 Times.
EXPLAIN_3_CON2=・The third shot's score
EXPLAIN_3_CON3=is doubled.

QUESTION_SWING_0_0=OK! Let's start!
QUESTION_SWING_0_1=Ready to Harvest!
QUESTION_SWING_1_0=Huh? Why's the tree swayin' like that?
QUESTION_SWING_1_1=Well, anyway, Let's Harvest!
QUESTION_SWING_2_0=The tree's shaking!
QUESTION_SWING_2_1=It's hard to hit, but keep tryin'!
QUESTION_SWING_3_0=You're pointing to the right!
QUESTION_SWING_3_1=Turn to the right!
QUESTION_SWING_4_0=You're pointing to the left!
QUESTION_SWING_4_1=Turn to the left!
QUESTION_SWING_5_0=It's swinging to the right!
QUESTION_SWING_5_1=Good luck hitting it right!
QUESTION_SWING_6_0=It's swingin' to the left!
QUESTION_SWING_6_1=If you hit it well, it'd be ve~ry~cool!
QUESTION_SWING_7_0=It's swaying quite a lot!
QUESTION_SWING_7_1=Hit that center and let's go!
QUESTION_SWING_8_0=The tree's swayin' to the rhythm!
QUESTION_SWING_8_1=It's groovin'!
QUESTION_SWING_9_0=The tree's shakin' too much!
QUESTION_SWING_9_1=Hey! Brother! Say somethin'!
QUESTION_SWING_10_0=Heyo, how much are you shakin'?
QUESTION_SWING_10_1=Well, let's show 'em our strength!
QUESTION_1KAIME1=1st Shot will cost $100
QUESTION_2KAIME1=2nd Shot will cost $200
QUESTION_3KAIME1=3rd Shot will cost $300
QUESTION_4KAIME1=4th Shot will cost $400
QUESTION_5KAIME1=5th Shot will cost $500
QUESTION_1KAIME2=Wanna try?
QUESTION_KAIME2=If you quit, there rest is gone. Wanna try?
QUESTION_ANS_YES1=OK! Get in the
QUESTION_ANS_YES2=Cannon and let's go!
QUESTION_1ANS_NO1=Oh no, are you quitting?
QUESTION_1ANS_NO2=When you get the nerve, come back for more!
QUESTION_1ANS_FEW_TIP1=You don't have enough coins!
QUESTION_1ANS_FEW_TIP2=Come back when you've got the dough.
QUESTION_2PRE1=Hey, Brother!
QUESTION_2PRE2=Is your body still OK?
QUESTION_3PRE1=After all those hits, are you OK?
QUESTION_3PRE2=Be a bit more careful!
QUESTION_4PRE1=If you keep doing this,
QUESTION_4PRE2=you'll get dizzy, alright?
QUESTION_5PRE1=One last shot!
QUESTION_5PRE2=You Ready?
QUESTION_2ANS_FEW_TIP1=You don't have enough coins!
QUESTION_2ANS_FEW_TIP2=So much for harvesting!
FUNKEY_COMPLETE1_1=OK! That's the end
FUNKEY_COMPLETE1_2=of the harvest for now!
FUNKEY_COMPLETE2_1=Next time, Aim for Perfection!
FUNKEY_COMPLETE2_2=Bye-Bye! Seeya next time!
QUESTION_NO_MORE1_1=Aw, DK, you're a mess.
QUESTION_NO_MORE1_2=Stop being so reckless!
QUESTION_NO_MORE2_1=Sorry, but that's all for today!
QUESTION_NO_MORE2_2=If more bananas grow, let's go!
QUESTION_FOLD_UP1_1=OK! That's the end
QUESTION_FOLD_UP1_2=of the harvest for now!
QUESTION_FOLD_UP2_1=The rest will be planted.
QUESTION_FOLD_UP2_2=If more bananas grow, let's go!
QUESTION_ORDER_CHANGED1=Try scoring from lowest to highest!
QUESTION_ORDER_CHANGED2=
QUESTION_FINAL_TERN1=The score doubles
QUESTION_FINAL_TERN2=at the end!
QUESTION_PLAYER1_READY1=Is Player 1 Ready?
QUESTION_PLAYER1_READY2=
QUESTION_PLAYER2_READY1=Is Player 2 Ready?
QUESTION_PLAYER2_READY2=
QUESTION_PLAYER3_READY1=Is Player 3 Ready?
QUESTION_PLAYER3_READY2=
QUESTION_PLAYER4_READY1=Is Player 4 Ready?
QUESTION_PLAYER4_READY2=
QUESTION_RETRY1=You don't need coins to retry!
QUESTION_RETRY2=Wanna try again?
QUESTION_ABORT1=Wanna quit?
QUESTION_ABORT2=

SCORE_BOARD_TERN1=1st Try
SCORE_BOARD_TERN2=2nd Try
SCORE_BOARD_TERN3=3rd Try
SCORE_BOARD_SUM=Total

YES=Yes
NO=No

OKANE=$
OKANE_RUBY=
SCORE=Score

SCORE_ORDER1=1st
SCORE_ORDER2=2nd
SCORE_ORDER3=3rd
