TITLE=Combo
STATUS=%sÅ^%s Notes Hit
CONDITION=Get a %s -note Combo!
CONDITION_2P=Get a %s -note Combo as a Duet!
COMMENT=\nTry to achieve a\%s -note Combo.
COMMENT_2P=You both should\ntry to achieve a\%s -note Combo.
COMMENT2=\nMiss a note and\nyour streak restarts.
COMMENT2_2P=If one of you misses a note\nyour combined streak restarts.
COMMENT3=\nWe're grooving!\nCan you hold your streak?
COMMENT3_2P=We're grooving!\nWill this duet hold on\nor get a GAME OVER?
SUCCESS=\nYou did it!\nYou got a %s -note Combo!
SUCCESS_2P=You did it!\nYou both got a %s -note Combo!
FAIL=Game Over.\nThe more notes you hit,\n the more the tree grows,\n remember?
FAIL_2P=Game Over.\nThe more notes you hit,\n the more the tree grows,\n remember?
CAUTION=

TITLE=Clap
STATUS=%sÅ@Å^%sÅ@Claps
CONDITION=Clap  %s Times
CONDITION_2P=Clap  %s Times together.
COMMENT=\nClap  %s Times
COMMENT_2P=You both have to clap  \n%s Times.
COMMENT2=\nClap Rolls also count!
COMMENT2_2P=Clap Rolls also count!
COMMENT3=\nBad and Missed\nClaps don't count.
COMMENT3_2P=Bad and Missed\nClaps don't count.
SUCCESS=You did it!\nYou Clapped %s Times!
SUCCESS_2P=You did it!\nYou Clapped %s Times!
FAIL=You Blew it.\n And I don't mean\nthe mic on your drum.
FAIL_2P=YGame Over.\nWhich one of you\ncut corners?
CAUTION=

TITLE=Pink Notes
STATUS=
CONDITION=Hit GREAT or OK on Pink Notes.
CONDITION_2P=Hit GREAT or OK on Pink Notes.
COMMENT=\nOnly Pink Notes count!
COMMENT_2P=Both of you must hit\nthe Pink Notes without fail.
COMMENT2=\nA BAD or Missed note will\nend the game quickly.
COMMENT2_2P=A BAD or Missed note will\nend the game quickly.
COMMENT3=\nThere seem to be more\nPink Notes than usual!
COMMENT3_2P=There seem to be more\nPink Notes than usual!
SUCCESS=You Did It!\nYou won the\nPink Note Challenge!
SUCCESS_2P=You did it!\nYou won the\nPink Note Challenge!
FAIL=Game Over.\nFocus on hitting\nboth sides at once.
FAIL_2P=Game Over.\nDon't ignore\nthe pink note.
CAUTION=

TITLE=Skulls
STATUS=%sÅ@Å^%sÅ@Notes
CONDITION=Avoid hitting all the Skulls.
CONDITION_2P=Avoid hitting all the Skulls.
COMMENT=\nPlease play the\nregular notes.
COMMENT_2P=Please play the\nregular notes.
COMMENT2=\nHitting Skulls\nresults in a GAME OVER.
COMMENT2_2P=Hitting Skulls\nresults in a GAME OVER.
COMMENT3=\nIf you know the song,\nyou should be careful.
COMMENT3_2P=Be careful\nand try not\nto hit Skulls.
SUCCESS=You did it!\nYou avoided all Skulls!
SUCCESS_2P=You did it!\nYou BOTH avoided the skulls!
FAIL=You blew it. It was difficult!\nBut don't fear skulls too much!
FAIL_2P=You got a GAME OVER,\nBut don't fear\nskulls too much!
CAUTION=

TITLE=Points
STATUS=%s Points
CONDITION=Try to get %s0,000 points.
CONDITION_2P=Try to get %s0,000 points together.
COMMENT=\nGet %s0,000 points!
COMMENT_2P=You both should score\n%s0,000 points, combined.
COMMENT2=\nIf you hit a skull note,\nYou get 0 Points.
COMMENT2_2P=If either of you\nhits a skull note\nYou'll both get 0 Points.
COMMENT3=You could get a higher score\nby getting a combo!
COMMENT3_2P=If you miss a beat,\nyou lose points!
SUCCESS=\nYou did it!\nMaybe %s0,000 points was too easy.
SUCCESS_2P=You did it!\nMaybe %s0,000 points was too easy.
FAIL=Game Over.\nAll because you're not keeping score.
FAIL_2P=Game Over.\nYou should be more\naware of the score.
CAUTION=

TITLE=Speed
STATUS=
CONDITION=Clear the song!
CONDITION_2P=Clear the song!
COMMENT=As usual,\nlike a Street Performance,\nwe'll clear the song.
COMMENT_2P=As usual,\nlike a Street Performance,\nwe'll clear the song.
COMMENT2=\nAs usual, the song's the same,\nbut it looks faster.
COMMENT2_2P=As usual, the song's the same,\nbut it looks faster.
COMMENT3=\nIf you know this one well,\nit's easy.
COMMENT3_2P=If you know this one well,\nit's easy.
SUCCESS=You did it! \nThe chart scrolled quick\nbut it's the same song.
SUCCESS_2P=You did it! \nThe chart scrolled quick\nbut it's the same song.
FAIL=Game Over.\nDon't focus on\nthe scroll speed.
FAIL_2P=Game Over.\nDon't focus on\nthe scroll speed.
CAUTION=

TITLE=POW
STATUS=
CONDITION=Hit a GREAT POW block
CONDITION_2P=Hit a GREAT POW block
COMMENT=\nHit the POW block\nwith GREAT timing.
COMMENT_2P=Hit the POW block\nwith GREAT timing.
COMMENT2=\nI don't know\nwhen the POW block's coming.
COMMENT2_2P=I don't know\nwhen the POW block's coming.
COMMENT3=\nWait and see.
COMMENT3_2P=If either of you miss, GAME OVER.
SUCCESS=\nPassed with Flying Colors.
SUCCESS_2P=\nPassed with Flying Colors.
FAIL=Game Over.\nIt's just ONE tap.
FAIL_2P=Game Over.\nIt's just ONE tap.
CAUTION=\nIt's coming up!

TITLE=Card Match
STATUS=
CONDITION=Match 3 %s Cards
CONDITION_2P=
COMMENT=Hit the STOP notes\nso the %s card\nstops spinning.
COMMENT_2P=
COMMENT2=Fox is GREAT\nKrystal is OK\nSlippy is BAD
COMMENT2_2P=
COMMENT3=There's usually\n3 STOP notes, but I don't\nknow what order\nthey'll be in.
COMMENT3_2P=
SUCCESS=You did it!\nYou got 3\n %s cards!
SUCCESS_2P=You did it!\nYou got 3\n %s cards!
FAIL=Game Over.\nYou didn't \nmatch the %s cards.
FAIL_2P=Game Over.\nYou didn't\nmatch the %s cards.
CAUTION=

TITLE=NES
STATUS=
CONDITION=Hit all GREAT or OK Notes.
CONDITION_2P=Hit all GREAT or OK Notes.
COMMENT=Miss one note\nand it's GAME OVER.
COMMENT_2P=Miss one note\nand it's GAME OVER.\n
COMMENT2=By the way-\nDid you unlock this\nsong for NES Hall Yet?
COMMENT2_2P=By the way-\nDid you unlock this\nsong for NES Hall Yet?
COMMENT3=\nYou're doing great!
COMMENT3_2P=\nYou're both doing great!
SUCCESS=You did it!\nSo you're good at\nNES Games, aren't you?
SUCCESS_2P=You did it!\nSo you're good at\nNES Games, aren't you?
FAIL=For this test,\nyou may need a\nbetter sense of games\nthan you have of music.
FAIL_2P=For this test,\nyou may need a\nbetter sense of games\nthan you have of music.
CAUTION=

TITLE=Battle
STATUS=
CONDITION=Defeat the COM in Battle Mode.
CONDITION_2P=
COMMENT=
COMMENT_2P=
COMMENT2=
COMMENT2_2P=
COMMENT3=
COMMENT3_2P=
SUCCESS=
SUCCESS_2P=
FAIL=
FAIL_2P=
CAUTION=

TITLE=Reflexes
STATUS=
CONDITION=Hit the notes that come out of nowhere!
CONDITION_2P=Hit the notes that come out of nowhere!
COMMENT=\nAim for 3 GREAT or OK Notes.
COMMENT_2P=Aim for 3 GREAT or OK Notes.
COMMENT2=You don't know when\nthe note's coming,\nso watch out.
COMMENT2_2P=You don't know when\nthe note's coming,\nso watch out.
COMMENT3=Wait patiently,\nand try not to hit\nSkulls.
COMMENT3_2P=If either of you\nmisses a regular note or \nhits a skull note, it's game over.
SUCCESS=\nThat's quite a set of reflexes you've got there!
SUCCESS_2P=Both of you have\ngreat reflexes!
FAIL=Game Over!\nI told you\nto watch out!!
FAIL_2P=Game Over!\nI told you\nto watch out!!
CAUTION=Aim for 3 Great or OK....

